import sge

WINDOW_WIDTH = 640
WINDOW_HEIGHT = 480

DIRECTION_LEFT = 3
DIRECTION_RIGHT = 1
DIRECTION_UP   = 4
DIRECTION_DOWN = 2
TURN_LEFT = -1
TURN_RIGHT = 1

ROTATE_INTERVAL = 1

MAP_SCALE = 50
MAP_WIDTH = 20
MAP_HEIGHT = 20
MAP_START  = 1
MAP_END    = 2
MAP_HORIZON    = 3
MAP_RIGHT_DOWN = 4
MAP_RIGHT_UP   = 5
MAP_LEFT_DOWN  = 6
MAP_LEFT_UP    = 7
MAP_VERTICLE   = 8

# [RIGHT,DOWN,LEFT,UP] in bits
FIELD_UP = 1
FIELD_DOWN = 4
FIELD_UP_DOWN = 5
FIELD_LEFT = 2
FIELD_RIGHT = 8
FIELD_LEFT_RIGHT = 10
FIELD_RIGHT_DOWN = 12
FIELD_RIGHT_UP = 9
FIELD_LEFT_DOWN = 6
FIELD_LEFT_UP = 3
FILED_R_UP = 14
FIELD_R_DOWN = 11
FIELD_R_LEFT = 13
FIELD_R_RIGHT = 7
FIELD_ALL = 15
FIELD_R_ALL = 0
FIELD_OUTLINE_COLOR = sge.gfx.Color('red')
FIELD_COLOR = sge.gfx.Color([255,0,0,50])
