import sge
DIRECTION_LEFT = 3
DIRECTION_RIGHT = 1
DIRECTION_UP   = 4
DIRECTION_DOWN = 2
TURN_LEFT = -1
TURN_RIGHT = 1

ROTATE_INTERVAL = 1

MAP_SCALE = 50
MAP_HORIZON    = 3
MAP_RIGHT_DOWN = 4
MAP_RIGHT_UP   = 5
MAP_LEFT_DOWN  = 6
MAP_LEFT_UP    = 7
MAP_VERTICLE   = 8
